# Copyright 2020 bmc::labs Gmbh. All rights reserved.
#
# Authors: Florian Eich <florian@bmc-labs.com>

stages:
  - test
  - doc

test:cargo:
  stage: test
  coverage: /^\s*lines:\s*\d+.\d+\%/
  tags:
    - coverage
    - rust
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - sh coverage.sh
  artifacts:
    paths:
      - target/coverage/html

pages:
  stage: doc
  tags:
    - rust
  needs:
    - test:cargo
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=xdrk">' > public/index.html
    - mkdir -p public/covr
    - cp -r target/coverage/html/* public/covr
  artifacts:
    paths:
      - public
  only:
    - trunk
